In [35]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [53]:
import pandas as pd
df = pd.read_csv('new.csv')
df.head()

,sym,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheels-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [54]:
df=df.replace('?', np.nan)
df

,sym,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheels-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [55]:
df=df.dropna()
df

,sym,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheels-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [57]:
df=df.drop(['sym', 'num-of-doors','drive-wheels','wheels-base','length','width','height','curb-weight','num-of-cylinders','fuel-system','bore','stroke','city-mpg','highway-mpg'], axis=1)

In [58]:
df

,make,fuel-type,aspiration,body-style,engine-location,engine-type,engine-size,compression-ratio,horsepower,peak-rpm,price
0,alfa-romero,gas,std,convertible,front,dohc,130,9.0,111,5000,13495
1,alfa-romero,gas,std,convertible,front,dohc,130,9.0,111,5000,16500
2,alfa-romero,gas,std,hatchback,front,ohcv,152,9.0,154,5000,16500
3,audi,gas,std,sedan,front,ohc,109,10.0,102,5500,13950
4,audi,gas,std,sedan,front,ohc,136,8.0,115,5500,17450
...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,sedan,front,ohc,141,9.5,114,5400,16845
201,volvo,gas,turbo,sedan,front,ohc,141,8.7,160,5300,19045
202,volvo,gas,std,sedan,front,ohcv,173,8.8,134,5500,21485
203,volvo,diesel,turbo,sedan,front,ohc,145,23.0,106,4800,22470
204,volvo,gas,turbo,sedan,front,ohc,141,9.5,114,5400,22625

In [63]:
df['make'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'saab',
       'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

### OHE

In [69]:
fuel = list(df['fuel-type'].unique())
num = list(range(len(fuel)))
# print(flowers)
# print(num)
mapping = dict(zip(fuel,num))
df['fuel-type']= df['fuel-type'].apply(lambda x: mapping[x])

In [70]:
fuel = list(df['aspiration'].unique())
num = list(range(len(fuel)))
# print(flowers)
# print(num)
mapping = dict(zip(fuel,num))
df['aspiration']= df['aspiration'].apply(lambda x: mapping[x])

In [71]:
fuel = list(df['body-style'].unique())
num = list(range(len(fuel)))
# print(flowers)
# print(num)
mapping = dict(zip(fuel,num))
df['body-style']= df['body-style'].apply(lambda x: mapping[x])

In [72]:
fuel = list(df['engine-location'].unique())
num = list(range(len(fuel)))
# print(flowers)
# print(num)
mapping = dict(zip(fuel,num))
df['engine-location']= df['engine-location'].apply(lambda x: mapping[x])


fuel = list(df['engine-type'].unique())
num = list(range(len(fuel)))
# print(flowers)
# print(num)
mapping = dict(zip(fuel,num))
df['engine-type']= df['engine-type'].apply(lambda x: mapping[x])

fuel = list(df['make'].unique())
num = list(range(len(fuel)))
# print(flowers)
# print(num)
mapping = dict(zip(fuel,num))
df['make']= df['make'].apply(lambda x: mapping[x])

In [73]:
df

,make,fuel-type,aspiration,body-style,engine-location,engine-type,engine-size,compression-ratio,horsepower,peak-rpm,price
0,0,0,0,0,0,0,130,9.0,111,5000,13495
1,0,0,0,0,0,0,130,9.0,111,5000,16500
2,0,0,0,1,0,1,152,9.0,154,5000,16500
3,1,0,0,2,0,2,109,10.0,102,5500,13950
4,1,0,0,2,0,2,136,8.0,115,5500,17450
...,...,...,...,...,...,...,...,...,...,...,...
200,20,0,0,2,0,2,141,9.5,114,5400,16845
201,20,0,1,2,0,2,141,8.7,160,5300,19045
202,20,0,0,2,0,1,173,8.8,134,5500,21485
203,20,1,1,2,0,2,145,23.0,106,4800,22470
204,20,0,1,2,0,2,141,9.5,114,5400,22625

In [ ]:
[0,0,0,0,0,0,130,9,111,5000]

## training the model

In [100]:
X=df.drop(['price'], axis=1)
Y=df['price']

In [101]:
model = LinearRegression()
model=model.fit(X,Y)

In [102]:
model.score(X,Y)

0.8452098364060834

In [105]:
import pickle
pickle.dump(model, open('model.pkl','wb'))